### ISSUE TITLE
Universal Scalable Firmware

### ISSUE THREAD

**Issue by xypron** [riscv/configuration-structure#112]
Involving the EDK II and U-Boot community a Universal Scalable Firmware Specification has been developped.  We should try to be conformant with that specification or to contribute to it. Cf. 
https://universalscalablefirmware.github.io/documentation/2_universal_payload.html#payload-interfaces

**Comment by sqzsq** [comment]
The payload interface described in the document is in fact the output of the parsing done by the boot-loader. It is not directly related to the configuration format we are defining here. In other words, if the boot-loader is conforming to the USFS, it will naturally generate the expected Hand Off Blocks (HOBs), such as device tree, after parsing the U/D configuration structure.

Closed after TG discussion.
