### ISSUE TITLE
Configuration structure is static

### ISSUE THREAD

**Issue by timsifive** [riscv/configuration-structure#114]
In the latest draft I don't see it mentioned that the configuration structure is static. I think it's important to clarify that the structure is the same every time it's read. It does not dynamically change between power-ups (e.g. when a USB device is plugged in).

**Comment by sqzsq** [comment]
Added description in [commit](https://github.com/riscv/configuration-structure/commit/f1636cfa29a727729420447edddb4b4fd8a272b2)
