### ISSUE TITLE
The way of storage for CS (Configuration Structure) and mconfigtr CSR

### ISSUE THREAD

**Issue by zhangdujiao** [riscv/configuration-structure#120]
1. What are the requirements or suggestions for the CS storage method: RAM, ROM, or non-volatile efuse? 

2. Is the mconfigtr CSR burned into efuse after tape-out? or it is written into firmware after tape-out, or it can be written by firmware after the boot?

3. Whether the mconfigtr can be read only after the core is powered on, or it can be read by a debugger from outside the cluster?

**Comment by pdonahue-ventana** [comment]
> 3. Whether the mconfigtr can be read only after the core is powered on, or it can be read by a debugger from outside the cluster?

I would expect that the external debugger would find the address of CS by reading confstrptr in the Debug Module.

**Comment by zhangdujiao** [comment]
> > 3. Whether the mconfigtr can be read only after the core is powered on, or it can be read by a debugger from outside the cluster?
> 
> I would expect that the external debugger would find the address of CS by reading confstrptr in the Debug Module.

yes, thanks, I want to know how to store the CS in SoC, maybe the efuse or other Nonvolatile memory？
