### ISSUE TITLE
Empty configuration structure entry causes compiler error

### ISSUE THREAD

**Issue by changab** [riscv/configuration-structure#18]
For example in scheman.json5, quick_access_command doesn't have any descriptions as below,
    quick_access_command: {
        // There are no options. If the option exists, then the feature is implemented.
    },
That generates an empty entry in schema.c with an unknown size compiler error on Visual Studio C. 

What is the purpose of an empty configuration structure defined in shcema?

**Comment by timsifive** [comment]
I don't see the compiler error you're reporting, but I agree that there is no point to this. I'll just change the type to a Boolean.
